library(tm)
library(wordcloud)
library(SnowballC)
texto_token = paste0("recuperação recuperam alunos que precisam ser recuperados")
corpus <- Corpus(VectorSource(texto_token))
corpus <- tm_map(corpus, removeWords, stopwords('pt'))
stemDocument(texto_token, language = "portuguese")
tdm <- as.matrix((TermDocumentMatrix(corpus, control=list(stemming = TRUE))))
dim(tdm)