library(tm)
library(wordcloud)
texto_token = paste0("recuperação recuperam alunos que precisam ser recuperados")
corpus <- Corpus(VectorSource(texto_token))
corpus <- tm_map(corpus, removeWords, stopwords('pt'))
tdm <- as.matrix((TermDocumentMatrix(corpus, control=list(stemming = TRUE))))
dim(tdm)
fre <- rowSums(tdm)
fre <- sort(fre,decreasing = TRUE)
head(fre)